name: b.push branch
on:
  #push:
    #branches:
     # - main
      #- dev
      #- "!feature"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a script
        run: echo "Iam triggered by event branch"
      - name: print a event
        run: echo ${{github.event_name}}