name: c.pathfiltering
on:
  push:
    paths:
      - "!feature/*"
      - "commit.txt"
      - "*.ts"
    #paths-ignore:
      #b- "commit"
jobs:
  build:
    runs-on: ubuntu-latest
    # runs-on: [self-hosted, linux, x64, production]
    steps:
      - uses: actions/checkout@v4
      - name: Run a Script
        run: echo "Hi Iam learning pathfilters"