name: a.basic structure flow
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a Script
        run: echo "Hi GitHub Actions World"