name: j.jobdependecy
on:
  workflow_dispatch:
    inputs:
      env:
        description: "enter key"
        type: choice
        options: [dev, stage]
jobs:
  gen-matrix:
    runs-on: ubuntu-latest
    steps:
      - run: echo "testing"

        # fan out
  deploy:
    runs-on: ubuntu-latest
    needs: gen-matrix
    steps:
      - run: echo "deployed"
  cancel:
    runs-on: ubuntu-latest
    needs: gen-matrix
    steps:
      - run: echo "deployed"
      - run: echo "deployed"

        # fan in
  allin:
    runs-on: ubuntu-latest
    needs: [gen-matrix, cancel]
    steps:
      - run: echo "cancelled"
        # job failure
  skip_tests:
    runs-on: ubuntu-latest
    needs: gen-matrix
    if: failure()
    steps:
      - run: echo "iam always"
