name: k.updownartifacts
on:
  workflow_dispatch:
    inputs:
      env:
        description: "Enter a env"
        type: choice
        options: [dev, stage]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Iam artifatcs" >> output.txt
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: testapp
          path: output.txt
          retention-days: 3
          if-no-files-found: error
          overwrite: true
          compression-level: 7
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: testapp
          path: artifacts
      - run: cat output.txt