# temurin,zulu,corretto,microsoft,oracle,graalvm/liberica
name: m.setupjava
on:
  workflow_dispatch:
    inputs:
      env:
        description: "Enter a value"
        type: choice
        options:
          - dev
          - stage
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup java jdk 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
      - name: Build with maven
        run: mvn clean package -DskipTests
        working-directory: springboot-demo
      - name: Run Unit test cases
        run: mvn test
        working-directory: springboot-demo
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: springboot-demo/target/*.jar
          retention-days: 30
          overwrite: true
          if-no-files-found: warn
          compression-level: 7