name: v.secretsvariables

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Choose env"
        type: choice
        options:
          - dev
          - stage
          - prod

jobs:
  exporesecrets:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.env }}

    steps:
      - name: Use environment secret
        run: echo "Secret is ${{ vars.IAMKING }}"

#vars.Name, secrets.Name