name: v.secretsvariables
on:
  workflow_dispatch:
jobs:
  exporesecrets:
    runs-on: ubuntu-latest
    steps:
      - run: echo " {{secrets.POSTGRES_PASSWORD}}"
      - run: echo " {{vars.POSTGRES_DB}}"