name: v.secretsvariables
on:
  workflow_dispatch:
jobs:
  exporesecrets:
    runs-on: ubuntu-latest
    steps:
      - name: Postgresspassword
        run: echo "${{secrets.POSTGRES_PASSWORD}}"
      - name: postgressdb
        run: echo "${{vars.POSTGRES_DB}}"