name: v.secretsvariables
on:
  workflow_dispatch:
    inputs:
      env:
        description: "Choose env"
        type: choice
        options:
          - dev
          - stage
          - prod
jobs:
  exporesecrets:
    runs-on: ubuntu-latest
    environment: ${{github.event.inputs.env}}
    steps:
      - name: Use environment secret
        if: ${{contains('dev')}}
        run: echo "deploying to dev started"
      - name: Usevar
        run: cat ${{vars.IAMKING}}
