name: y.reusablebuildworkflow
on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: '17'
      environment:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building for ${{ inputs.environment}}"