name: z.callerci
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: dev
jobs:
  call-ci:
    uses: sreeharinath1/github_action/.github/workflows.reusableworkflow,yam@main
    with:
      environment: prod