name: z.callerci
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: dev
jobs:
  call-ci:
    uses: sreeharinath1/github_actions/.github/workflows/25.reusableworkflow.yaml@main
    with:
      java-version: 17
      environment: prod