name: zk.debug
on:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug logs'
        required: false
        default: 'false'

jobs:
  debug-job:
    runs-on: ubuntu-latest
    steps:
      - name: Enable debug if requested
        if: ${{ github.event.inputs.debug == 'true' }}
        run: |
          echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV
          echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV
