name: zm.snyk
on:
  workflow_dispatch:

jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin

      - name: Build Project
        run: mvn clean package -DskipTests
        working-directory: springboot-demo

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth $SNYK_TOKEN  # Explicitly authenticate before scan

      - name: Run Snyk vulnerability scan
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --maven-aggregate-project --sarif-file-output=snyk.sarif --severity-threshold=high
        working-directory: springboot-demo

      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: springboot-demo/snyk.sarif

      - name: Monitor project with Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk monitor --maven-aggregate-project
        working-directory: springboot-demo