name: e.manualtriggger
on:
  workflow_dispatch:
    inputs:
      environments:
        description: "Select env"
        type: choice
        required: true
        options: [prod, dev, stage]
      skip_tests:
        description: "Select TEST"
        type: boolean
        required: false
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Ran a Script
        run: echo "iam running"