name: f.githubcontext
on:
  workflow_dispatch:
    inputs:
      env:
        description: "Enter a ENV"
        type: choice
        required: true
        options:
          - dev
          - stage
          - prod
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a Script
        run: echo "Iam example of context"
      - name: Print a branch
        run: echo ${{ github.ref}}
      - name: print a event
        run: echo ${{github.event_name}}