name: f.githubcontext
on:
  workflow_dispatch:
    inputs:
      env:
        description: "Enter a ENV"
        type: choice
        required: true
        options:
          - dev
          - stage
          - prod
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a Script
        run: echo "Iam example of context"
      - name: Print a branch
        run: echo ${{ github.ref}}
      - name: print a ref name clean branch name
        run: echo ${{github.ref_name}}
      - name: print a sha
        run: echo ${{github.sha}}
      - name: print actor or who running
        run: echo ${{github.actor}}
      - name: print repo
        run: echo ${{github.repository}}
      - name: print a runnerid
        run: echo ${{github.run_id}}
      - name: print a run_number
        run: echo ${{github.run_number}}
      - name: print a server url
        run: echo ${{github.server_url}}
      - name: printing runner context
        run: |
          echo "Runner Os: ${{runner.os}}"
          echo "Runner arch: ${{runner.arch}}"
          echo "runner name: ${{runner.name}}"
          echo "runner tool cache: ${{runner.tool_cache}}"
          echo "runner debug: ${{runner.debug}"
