name: j.dynamicmatrices
on:
  workflow_dispatch:
    inputs:
      env:
        description: " enter a key"
        type: choice
        options: [dev, stage]
jobs:
  prod_gen:
    runs-on: ubuntu-latest
    steps:
      - id: prod-matrix
        run: |
          echo "prod_matrix={\"include\":[{\"env\":\"${{ github.event.inputs.env }}\"}]}" >> $GITHUB_OUTPUT
    outputs:
      prod_matrix: ${{ steps.prod-matrix.outputs.prod_matrix }}

  prod:
    needs: prod_gen
    strategy:
      matrix: ${{ fromJSON(needs.prod_gen.outputs.prod_matrix) }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to ${{ matrix.env }}"
